import sqlite3

connection = sqlite3.connect("security_logs.db")
cursor = connection.cursor()

cursor.execute('''
    SELECT source_ip, COUNT(*) as total_attacks
    FROM incidents
    WHERE severity = "HIGH"
    GROUP BY source_ip
    HAVING total_attacks >= 5
    ORDER BY total_attacks DESC
''')

banned_ips = cursor.fetchall()

with open("firewall_rules.txt", "w") as file:
    file.write("# AUTOMATIC FIREWALL BLOCKLIST\n")
    file.write("# Generated by Python Security Analyzer\n\n")

    for record in banned_ips:
        ip_address = record[0]
        file.write(f"deny {ip_address}\n")

connection.close()

print(f"Blocklist generated successfully! {len(banned_ips)} IPs banned.")